experiments:
  - name: "mod_add_p97_v2"
    task:
      p: 97
      op: "add"
    model:
      hidden_dim: 128
      num_layers: 3
    training:
      epochs: 20
      batch_size: 128
    seeds: [42, 123, 1024]
    optimizers:
      - name: "BelOpt"
        params:
          lr: 1.0e-3
          gamma: 1.0e-4
          beta: 1.0e-3
          use_adaptive_gamma: True
      - name: "Adam"
        params:
          lr: 1.0e-3
      - name: "SGD"
        params:
          lr: 1.0e-2
          momentum: 0.9
      - name: "RMSProp"
        params:
          lr: 1.0e-3

  - name: "mod_mult_p97_v2"
    task:
      p: 97
      op: "multiply"
    model:
      hidden_dim: 256
      num_layers: 4
    training:
      epochs: 30
      batch_size: 128
    seeds: [42, 123, 1024]
    optimizers:
      - name: "BelOpt"
        params:
          lr: 1.0e-3
          gamma: 1.0e-4
          beta: 1.0e-3
          use_adaptive_gamma: True
      - name: "Adam"
        params:
          lr: 1.0e-3
      - name: "SGD"
        params:
          lr: 1.0e-2
          momentum: 0.9
      - name: "RMSProp"
        params:
          lr: 1.0e-3
